name: xmlrpc_server
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml_rpc: ^0.4.0
#  path: ^1.6.0

dev_dependencies:
  test: ^1.19.3